# syntax=docker/dockerfile:1
FROM node:16-alpine
WORKDIR /app
RUN npm install -g nodemon
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install
COPY . .
CMD ["npx","ts-node","--transpile-only","./src/scripts/runDailyCron.ts"]




